<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="1" failed="1" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2018-12-21T00:55:55Z" name="Default suite" finished-at="2018-12-21T00:55:56Z" duration-ms="1668">
    <groups>
    </groups>
    <test started-at="2018-12-21T00:55:55Z" name="Default test" finished-at="2018-12-21T00:55:56Z" duration-ms="1668">
      <class name="com.edu.interfacetest.HttpclientTestDemo4">
        <test-method signature="getAddress()[pri:0, instance:com.edu.interfacetest.HttpclientTestDemo4@687e99d8]" started-at="2018-12-21T00:55:55Z" name="getAddress" finished-at="2018-12-21T00:55:56Z" duration-ms="1562" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getAddress -->
        <test-method signature="getTransportFee()[pri:0, instance:com.edu.interfacetest.HttpclientTestDemo4@687e99d8]" started-at="2018-12-21T00:55:56Z" name="getTransportFee" finished-at="2018-12-21T00:55:56Z" depends-on-methods="com.edu.interfacetest.HttpclientTestDemo4.getAddress" duration-ms="63" status="FAIL">
          <exception class="net.sf.json.JSONException">
            <message>
              <![CDATA[null object]]>
            </message>
            <full-stacktrace>
              <![CDATA[net.sf.json.JSONException: null object
at net.sf.json.JSONObject.verifyIsNull(JSONObject.java:2744)
at net.sf.json.JSONObject.getJSONArray(JSONObject.java:2033)
at com.edu.interfacetest.HttpclientTestDemo4.getTransportFee(HttpclientTestDemo4.java:54)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- net.sf.json.JSONException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getTransportFee -->
        <test-method signature="submitOrder()[pri:0, instance:com.edu.interfacetest.HttpclientTestDemo4@687e99d8]" started-at="2018-12-21T00:55:56Z" name="submitOrder" finished-at="2018-12-21T00:55:56Z" depends-on-methods="com.edu.interfacetest.HttpclientTestDemo4.getTransportFee" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method HttpclientTestDemo4.submitOrder()[pri:0, instance:com.edu.interfacetest.HttpclientTestDemo4@687e99d8] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method HttpclientTestDemo4.submitOrder()[pri:0, instance:com.edu.interfacetest.HttpclientTestDemo4@687e99d8] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:887)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
      </class> <!-- com.edu.interfacetest.HttpclientTestDemo4 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
